services:
  ordering-api:
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile  # Arahkan ke Dockerfile yang benar
    ports:
      - "80:80"  # Port untuk HTTP
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I=
      - Jwt__Issuer=santaitechnology-api.com
      - Jwt__Audience=santaitechnology-api.com
      - KMS_SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I= 
      - AWS__AccessID=AKIAYS2NP3RU6DEGPJUM
      - AWS__SecretKey=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
      - AWS__Region=ap-southeast-1
      - Database__ConnectionString=Server=santaiproductiondatabase.cpca622mwdeq.ap-southeast-1.rds.amazonaws.com,1433;Database=ordering;User Id=santaitechnology;Password=_SANTAItechnology2024;Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;
      - Messaging__Host=amqps://b-7be94d57-3bad-4a58-862f-b64b5a6aa5f1.mq.ap-southeast-1.amazonaws.com:5671
      - Messaging__Username=santaitechnology
      - Messaging__Password=_SANTAItechnology2024
      - Cache__Host=santaimvprediscache-hkpg4d.serverless.apse1.cache.amazonaws.com:6379 
      - SafelyShutdown__Shutdown=false 
      - SenangPay__Host=https://app.senangpay.my/payment
      - SenangPay__MerchantId=741172360948037
      - SenangPay__SecretKey=6936-735
      - AccountService__Host=
      - CatalogService__Host=
      - MasterDataService__Host=

    restart: always