services:
  account-api:
    build:
      context: .
      dockerfile: Account.API/Dockerfile  # Arahkan ke Dockerfile yang benar
    ports:
      - "80:80"  # Port untuk HTTP
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Staging
      - Jwt__SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I=
      - Jwt__Issuer=santaitechnology-api.com
      - Jwt__Audience=santaitechnology-api.com
      - KMS_SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I= 
      - AWS__AccessID=AKIAYS2NP3RU6DEGPJUM
      - AWS__SecretKey=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
      - AWS__Region=ap-southeast-1
      - Database__ConnectionString=Server=development.cpca622mwdeq.ap-southeast-1.rds.amazonaws.com,1433;Database=account;User Id=santaitechnology;Password=_SANTAItechnology2024;Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;
      - Messaging__Host=amqps://b-e7d48130-52b4-4deb-9718-410459aa94ed.mq.ap-southeast-1.amazonaws.com:5671
      - Messaging__Username=santaitechnology
      - Messaging__Password=_SANTAItechnology2024
      - SafelyShutdown__Shutdown=false 
      - Cache__Host=santaimvprediscache-hkpg4d.serverless.apse1.cache.amazonaws.com:6379
      - ReferralProgram__ValidMonth=4
      - ReferralProgram__Point=100
    restart: always