services:
  ordering-api:
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile  # Arahkan ke Dockerfile yang benar
    ports:
      - "80:80"  # Port untuk HTTP
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Staging
      - Jwt__SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I=
      - Jwt__Issuer=santaitechnology-api.com
      - Jwt__Audience=santaitechnology-api.com
      - KMS_SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I= 
      - AWS__AccessID=AKIAYS2NP3RU6DEGPJUM
      - AWS__SecretKey=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
      - AWS__Region=ap-southeast-1
      - Database__ConnectionString=Server=development.cpca622mwdeq.ap-southeast-1.rds.amazonaws.com,1433;Database=ordering;User Id=santaitechnology;Password=_SANTAItechnology2024;Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;
      - Messaging__Host=amqps://b-e7d48130-52b4-4deb-9718-410459aa94ed.mq.ap-southeast-1.amazonaws.com:5671
      - Messaging__Username=santaitechnology
      - Messaging__Password=_SANTAItechnology2024
      - Cache__Host=santaimvpstagingv2.hkpg4d.clustercfg.apse1.cache.amazonaws.com:6379
      - Cache__Ssl=false
      - SafelyShutdown__Shutdown=false 
      - SenangPay__Host=https://app.senangpay.my/payment
      - SenangPay__MerchantId=741172360948037
      - SenangPay__SecretKey=6936-735
      - AccountService__Host=http://internal-AccountServiceLoadBalancer-783549570.ap-southeast-1.elb.amazonaws.com:80
      - CatalogService__Host=http://internal-CatalogServiceLoadBalancer-1634552484.ap-southeast-1.elb.amazonaws.com:80
      - MasterDataService__Host=http://internal-MasterDataLoadBalancer-188755112.ap-southeast-1.elb.amazonaws.com:80

    restart: always