services:
  catalog-api:
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile  # Arahkan ke Dockerfile yang benar
    ports:
      - "80:80"  # Port untuk HTTP
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Staging
      - Jwt__SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I=
      - Jwt__Issuer=santaitechnology-api.com
      - Jwt__Audience=santaitechnology-api.com
      - KMS_SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I= 
      - AWS__AccessID=AKIAYS2NP3RU6DEGPJUM
      - AWS__SecretKey=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
      - AWS__Region=ap-southeast-1
      - Database__ConnectionString=Server=ec2-18-143-178-237.ap-southeast-1.compute.amazonaws.com,1433;Database=catalog;User Id=sa;Password=_SANTAItechnology2024;Trusted_Connection=False;Encrypt=False;TrustServerCertificate=True;
      - Messaging__Host=ec2-18-143-178-237.ap-southeast-1.compute.amazonaws.com:5672
      - Messaging__Username=santaitechnology
      - Messaging__Password=_SANTAItechnology2024
      - Cache__Host=ec2-18-143-178-237.ap-southeast-1.compute.amazonaws.com:6379
      - Cache__Ssl=false
    restart: always