version: '3.9'

services:
    rabbitmq:    
        image: rabbitmq:3-management
        container_name: rabbitmq-santai
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: eris
            RABBITMQ_DEFAULT_PASS: 000328Eris@
        restart: always
        networks:
            - backend-network
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        container_name: elasticsearch-santai
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - es_data:/usr/share/elasticsearch/data
        restart: always 
        networks:
            - backend-network
    dynamodb:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb-santai
        ports:
            - "8000:8000"
        restart: always
        networks:
            - backend-network
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: erisekasaputra28
            MINIO_ROOT_PASSWORD: 000328Eris@
        volumes:
            - minio-data:/data
            - minio-config:/root/.minio
        command: server /data --console-address ":9001"
        restart: always
        networks:
            - backend-network
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend-network 
            


volumes:
    es_data:
    minio-data:
    minio-config:

networks:
    backend-network:
        driver: bridge