version: '3.9'

services:
    rabbitmq:    
        image: rabbitmq:3-management
        container_name: rabbitmq-santai
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=santaitechnology
            - RABBITMQ_DEFAULT_PASS=_SANTAItechnology2024
        restart: always
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq 
            - rabbitmq_logs:/var/log/rabbitmq
        networks:
            - backend-network   
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379" 
        volumes:
            - redis_data:/data
        networks:
            - backend-network  
        restart: always
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=_SANTAItechnology2024
        ports:
          - "1433:1433"
        volumes:
          - sql_data:/var/opt/mssql
        networks:
          - backend-network  
        restart: always
volumes:
    sql_data: 
    rabbitmq_data:   # Volume untuk data RabbitMQ
    rabbitmq_logs:   # Volume untuk log RabbitMQ
    redis_data:
networks:
    backend-network:
        driver: bridge