version: '3.0'

services:
  sqlinstance:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlinstance
    restart: always
    ports:
      - 1433:1433
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=000328Eris@"