services:
  chat-api:
    build:
      context: .
      dockerfile: Chat.API/Dockerfile   
    ports:
      - "80:80"  
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Staging
      - Jwt__SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I=
      - Jwt__Issuer=santaitechnology-api.com
      - Jwt__Audience=santaitechnology-api.com
      - KMS_SecretKey=tP56kzHlfp+IUY/nhdOFbOsRjOSEbTVv6sexU/JL17I=
      - Google__ClientSecret=testing
      - AWS__AccessID=AKIAYS2NP3RU6DEGPJUM
      - AWS__SecretKey=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
      - AWS__Region=ap-southeast-1 
      - Messaging__Host=rabbitmq://175.41.148.241:5672
      - Messaging__Username=santaitechnology
      - Messaging__Password=_SANTAItechnology2024
      - Cache__Host=175.41.148.241:6379
      - Cache__Ssl=false
      - DynamoDB__Chat__TableName=SantaiChat
      - DynamoDB__Chat__PartitionKey=chatKey
      - DynamoDB__Chat__SortKey=timestamp
       
    restart: always