using Core.Extensions; 
using Search.Worker; 
using Search.Worker.Extensions;   
var builder = Host.CreateApplicationBuilder(args); 
builder.AddHostedCoreOptionConfiguration();
builder.Services.AddMasstransitContext();
builder.Services.AddMediatorService<ISearchWorkerMarkerInterface>();
builder.Services.AddApplicationService();  
var host = builder.Build();
host.Run();
